# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3913ada050c7e671cc184614fd03924164baea731a824e986ec205a87ffe64153496bf29e4e101d0d207116fa38be329efbc6a2d645249e1741fcc800ce31610

test:
  secret_key_base: 2290068b6fe43f856763578adfaa766d32607c8a9b14fc06fe36f7fa123caa2f99c22470e955c577027db616853a5682e0a4a85d1b0b16faa8c0a0b2957e87b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
